#####################################################################################
#### NOTE: head over to `builds.yaml` to define what builds you'd like to run. ####
#### (i.e., datasets and subsampling schemas)  ####
#####################################################################################

# This analysis-specific config file overrides the settings in the default config file.
# If a parameter is not defined here, it will fall back to the default value.

configfile:
  - defaults/parameters.yaml # Pull in the default values
  - my_profiles/usaf/builds.yaml # Pull in our list of desired builds

config:
  - sequences=/sample/tmp-tf-ton01/workspace/nextstrain_data/sequences_2021-02-05_08-24.fasta
  - metadata=/sample/tmp-tf-ton01/workspace/nextstrain_data/metadata_2021-02-05_19-03.tsv

# Set the maximum number of cores you want Snakemake to use for this pipeline.
cores: 12

# Always print the commands that will be run to the screen for debugging.
printshellcmds: True

# Print log files of failed jobs
show-failed-logs: True
